### ISSUE TITLE
[Lizard]: Wensen admin

### ISSUE THREAD

**Issue by lisannewapstra** [nens/servicedesk-issue-only#38]
- [x] nens/lizard-nxt#5462
- [x] nens/nens-auth-client#72
- [x] nens/nens-auth-client#73

### Contact Details

Lisanne & Florian

### Incident Type

Wish

### What priority should we assign to this submission?

Prio3 Not urgent

### Request

Voor applicatiebeheer Lizard zou het fijn zijn als er weer wat aanpassingen in de Lizard admin gedaan kunnen worden. We zullen ze hier verzamelen.

- https://demo.lizard.net/admin/lizard_nxt/scenario/ zoekbaar maken op uuid
- https://demo.lizard.net/admin/lizard_auth_client/userorganisationrole/add/ niet alleen dropdown, maar ook zoekbalk voor user en organisation. De lijsten worden te lang
- https://demo.lizard.net/admin/lizard_nxt/sos2importer/ mag verwijderd worden. Is leeg/niet meer gebruikt
- https://demo.lizard.net/admin/lizard_auth_client/organisation/ voeg datum aanmaken toe als mogelijk
- https://demo.lizard.net/admin/hydra_core/monitoringnetwork/ maak filterbaar op organisation

@JJFlorian voeg vooral je wensen/ideeën hieraan toe

**Comment by lexvand** [comment]
@lisannewapstra 
Bedankt voor deze wensen. Hierbij mijn reactie:

- Punt 1 en 5 zijn helder en zijn naar verwachting eenvoudig te implementeren
- Bij punt 2 is het even de vraag of we een beter alternatief kunnen vinden. De huidige `<select>` velden ondersteunen zoeken op de beginletters door te typen als je het veld geselecteerd hebt. Op die manier gaat het instellen in de meeste gevallen juist heel snel, is mijn ervaring. Door er raw_id_field (Django term) van te maken (zie bijv. selectie organisatie voor een raster layer) moet je standaard telkens een nieuw menu openen, wat misschien juist meer handelingen met zich meebrengt.
- Punt 3: Opruimen doe ik liever als we de gehele functionaliteit verwijderen.
- Punt 4 begrijp ik niet helemaal. Wil je hier de eigenschap `created` kunnen zien als je een organisatie opent?
